name: GeyserModelEngine
version: '${project.version}'
main: re.imc.geysermodelengine.GeyserModelEngine
authors:
  - zimzaza4
  - willem.dev
  - Roch Blondiaux
api-version: '1.19'
depend:
  - ModelEngine
  - floodgate
  - packetevents
commands:
  geysermodelengine:
    usage: /geysermodelengine reload
    permission: geysermodelengine.reload